// Copyright 2018 Bernhard Reitinger. All rights reserved.

package rex_test

import (
	"log"

	"github.com/breiting/rex"
)

func ExampleNewClient() {

	clientID := "855889020987285jklj2345j"   // generated by REX, this is only an example
	clientSecret := "Aasjdji09948jr4j3hllkj" // generated by REX, this is only an example

	client, err := rex.NewClient(clientID, clientSecret, nil)

	if err != nil {
		log.Fatal(err)
	}

	_ = client

	// Output:
	// client for subsequent calls
}
